let d = new Date()
// console.log(d)
// console.log(d.getDate())
// console.log(d.getMonth())
// console.log(d.getFullYear())
// console.log(d.getHours())
// console.log(d.getMinutes())
// console.log(d.getSeconds())
// console.log(d.getMilliseconds())
// console.log(d.getDay())
// console.log(d.getTime())
// console.log(Date.now())

console.log(d)
d.setFullYear(2023)
d.setMonth(6)
d.setDate(6)
console.log(d)